services:

    juntagrico:
      build:
        context: .
        args:
          juntagrico_username: test
          juntagrico_email: test@test.ch
          juntagrico_password: test
          juntagrico_secret_key: test
      environment:
        - JUNTAGRICO_EMAIL_HOST=mailhog
        - JUNTAGRICO_EMAIL_PORT=1025
        #- JUNTAGRICO_DEBUG=false

      depends_on: 
        - mailhog
      ports:
        - "8000:8000"

    mailhog:
      image: mailhog/mailhog
      ports:
        - "8025:8025"
