# Generated by Django 5.2.17 on 2026-09-16 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gartenberg', '0001_initial'),
        ('juntagrico', '0052_migrate_subscriptionsize_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTypeProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='juntagrico.productsize', verbose_name='Produktgrösse')),
                ('subscription_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depot_list_product_size', to='juntagrico.subscriptiontype', verbose_name='Abo-Typ')),
            ],
            options={
                'verbose_name': 'Produktgrösse auf Depotliste',
                'verbose_name_plural': 'Produktgrösse auf Depotliste',
            },
        ),
    ]
